# The Makefile
#
# Assumes the environment variables GOROOT, GOARCH, and GOOS are all set correctly.
#

include $(GOROOT)/src/Make.$(GOARCH)

all : MyTronBot

TARG=MyTronBot

GOFILES=\
	MyTronBot.go \
	Board.go

include $(GOROOT)/src/Make.cmd
